# Generated by Django 2.2.12 on 2020-12-27 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20201227_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='book',
            field=models.ManyToManyField(related_name='book_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
