# Generated by Django 2.2.12 on 2020-12-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='totalregisters',
        ),
    ]
